const bankLabels = [
  { code: '0102', name: 'Venezuela' },
  { code: '0104', name: 'Venezolano de Crédito' },
  { code: '0105', name: 'Mercantil' },
  { code: '0108', name: 'Provincial' },
  { code: '0114', name: 'Bancaribe' },
  { code: '0115', name: 'Exterior' },
  { code: '0116', name: 'B.O.D' },
  { code: '0128', name: 'Caroní' },
  { code: '0134', name: 'Banesco' },
  { code: '0137', name: 'Sofitasa' },
  { code: '0138', name: 'Banco Plaza' },
  { code: '0146', name: 'Banco de la Gente Emprendedora' },
  { code: '0149', name: 'Banco del Pueblo Soberano' },
  { code: '0151', name: 'BFC' },
  { code: '0156', name: '100% Banco' },
  { code: '0157', name: 'DelSur Banco Universal' },
  { code: '0163', name: 'Tesoro' },
  { code: '0166', name: 'Banco Agrícola de Venezuela' },
  { code: '0168', name: 'Bancrecer' },
  { code: '0169', name: 'Mi Banco' },
  { code: '0171', name: 'Banco Activo' },
  { code: '0172', name: 'Bancamiga' },
  { code: '0174', name: 'Banplus' },
  { code: '0175', name: 'Bicentenario - BDT' },
  { code: '0177', name: 'Banfanb' },
  { code: '0190', name: 'Citibank Venezuela' },
  { code: '0191', name: 'BNC' },
  { code: '0601', name: 'Instituto Municipal de Crédito Popular' },
  { code: '9999', name: 'Efectivo' }
];
export default bankLabels